services:
  alias-api-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: alias-api
    env_file: .env
    ports:
      - "[::1]:6777:6777"
      - "127.0.0.1:6777:6777"
    networks:
      - oas

networks:
  oas:
    external: true