// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package q

import (
	"time"
)

type Credit struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"userId"`
	Balance   int64     `json:"balance"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Destination struct {
	ID                      int64     `json:"id"`
	UserID                  int64     `json:"userId"`
	Username                string    `json:"username"`
	DestinationEmail        string    `json:"destinationEmail"`
	Domain                  string    `json:"domain"`
	CloudflareDestinationID string    `json:"cloudflareDestinationId"`
	IsVerified              bool      `json:"isVerified"`
	CreatedAt               time.Time `json:"createdAt"`
	UpdatedAt               time.Time `json:"updatedAt"`
}

type Payment struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"userId"`
	Type      string    `json:"type"`
	Gateway   string    `json:"gateway"`
	TxnID     string    `json:"txnId"`
	Amount    int64     `json:"amount"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Rule struct {
	ID               int64     `json:"id"`
	UserID           int64     `json:"userId"`
	Username         string    `json:"username"`
	AliasEmail       string    `json:"aliasEmail"`
	DestinationEmail string    `json:"destinationEmail"`
	IsActive         bool      `json:"isActive"`
	Comment          string    `json:"comment"`
	Name             string    `json:"name"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type SocialProfile struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"userId"`
	Username  string    `json:"username"`
	Github    string    `json:"github"`
	Google    string    `json:"google"`
	Facebook  string    `json:"facebook"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Subscription struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"userId"`
	CreditID  int64     `json:"creditId"`
	Plan      string    `json:"plan"`
	Price     int64     `json:"price"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Status    string    `json:"status"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	IsEmailVerified   bool      `json:"isEmailVerified"`
	AliasCount        int64     `json:"aliasCount"`
	DestinationCount  int64     `json:"destinationCount"`
	IsPremium         bool      `json:"isPremium"`
	Password          string    `json:"password"`
	Provider          string    `json:"provider"`
	Avatar            string    `json:"avatar"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
	Active            bool      `json:"active"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type UserAuth struct {
	ID                   int64     `json:"id"`
	UserID               int64     `json:"userId"`
	Username             string    `json:"username"`
	PasswordResetToken   string    `json:"passwordResetToken"`
	PasswordResetExpires time.Time `json:"passwordResetExpires"`
	CreatedAt            time.Time `json:"createdAt"`
	UpdatedAt            time.Time `json:"updatedAt"`
}
