name: Build and Release Go Binary

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]  # Target platforms: Linux and macOS
        goarch: [amd64, arm64]  # Architectures: x86_64 and ARM64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Build binary
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -ldflags "-X 'github.com/thanksduck/alias-api/cfconfig.allowedDomains=domain1.com,domain2.com' -X 'github.com/thanksduck/alias-api/cfconfig.configJSON=$(cat config.default.json | tr -d '\n')'" \
          -o dist/alias-api-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Create tar.gz archive
        run: |
          cd dist
          tar -czf alias-api-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz alias-api-${{ matrix.goos }}-${{ matrix.goarch }}
          rm alias-api-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz